### ISSUE TITLE
fizzbuzz  구현

### ISSUE THREAD

**Issue by Earlssu** [Team-Achivers/team-fb#1]
## Description
- 기존의 fizzbuzz 기능 구현

## Tasks
- [x] 3의 배수일 때 'fizz' 출력
- [x] 5의 배수일 때 'buzz' 출력
- [x] 15의 배수일 때 'fizzbuzz' 출력

## References
- 없습니다.

**Comment by gkwjdtk09** [comment]
good to go
